artgris_file_manager:
    conf:
        default:
            dir: "../public/uploads"
        files:
            dir: "../public/uploads"
            type: 'file'
        images:
            dir: "../public/uploads"
            type: 'image'