version: '3'
services:
  nginx:
    container_name: school_nginx
    build: config/docker/nginx
    ports:
      - '8082:80'
    volumes:
      - './:/var/www/html/'
      - './config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
  php:
    container_name: school_php
    build: config/docker/php
    volumes:
      - './:/var/www/html/'
      - './config/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - './config/docker/php/apcu.ini:/usr/local/etc/php/conf.d/docker-php-ext-apcu.ini'
  mysql:
    container_name: school_mysql
    image: mariadb
    ports:
      - '3302:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: school
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
  mail:
    container_name: school_mail
    image: mailhog/mailhog
    ports:
      - '8026:8025'
