#index:
#    path: /
#    controller: App\Controller\DefaultController::index
artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller/ManagerController.php"
    type:     attribute
    prefix:   /admin/art-file-manager